/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface CustomerRequestBody { 
    id?: number;
    firstname?: string;
    lastname?: string;
    email?: string;
    shippingAddress?: Address;
    paymentAddress?: Address;
    paymentOptions?: Array<string>;
    soldArticles?: Array<string>;
    boughtArticles?: Array<string>;
    bids?: Array<string>;
}

