/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Link } from './link';


export interface EntityModelCustomer { 
    firstname?: string;
    lastname?: string;
    email?: string;
    shippingAddress?: Address;
    paymentAddress?: Address;
    _links?: { [key: string]: Link; };
}

